version: '3.12'

services:
  analytics-mongo-db:
    image: mongo:latest
    container_name: analytics_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  test-mongo:
    image: mongo:latest
    container_name: test_mongo
    ports:
      - "27018:27017"

  todo_analytics:
    build:
      context: .
    ports:
      - "8002:8000"
    depends_on:
      - analytics-mongo-db
    env_file:
      - .env
    entrypoint:
      - ./entrypoint.sh
    networks:
      - app-network
      - kafka-net


volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
  kafka-net:
    external: true