name: Run tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27018:27017

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install poetry
      uses: abatilo/actions-poetry@v2

    - name: Install dependencies
      run: poetry install

    - name: Test with pytest
      env:
        MONGO_INITDB_ROOT_USERNAME: "testuser"
        MONGO_INITDB_ROOT_PASSWORD: "testpassword"
        MONGO_HOST: "localhost"
        MONGO_PORT: "27018"
        MONGO_DB_NAME: "test_db"
        KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
      run: poetry run pytest tests
