name: Run tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27018:27017

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install poetry
      uses: abatilo/actions-poetry@v2

    - name: Install dependencies
      run: poetry install

    - name: Test with pytest
      env:
        MONGO_URI: "mongodb://localhost:27018"
      run: poetry run pytest tests
